config/routes.rb
Rails.application.routes.draw do
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  before_save {email.downcase!}

  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  has_secure_password


  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(session_params[:email].downcase)
    if @user&.authenticate(session_params[:password])
      log_in @user
      redirect_to @user
    else
      flash.now[:danger] = "invalid email/password combination"
      render :new
    end
  end

  def destroy

  end


  private
    def session_params
      params.require(:session).permit(:email,:password)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ようこそ!"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = "")
    base_title = "Gathers"
    base_title += " : #{page_title}" unless page_title.empty?
    base_title
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class:"gravatar")
  end

end

app/views/layouts/_flash_messages.html.slim
- flash.each do |type,message|
  = content_tag(:div, message, class:"alert alert-#{type}")
    = message

app/views/layouts/_footer.html.slim
footer.footer.text-center.text-muted
  small &copy;
  | 2020 Gathers by k.suzuki

app/views/layouts/_head.html.slim
meta charset="utf-8"
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

= csrf_meta_tags
= csp_meta_tag

link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
= render "layouts/support_IE9"

app/views/layouts/_header.html.slim
header
  nav.navbar.navbar-fixed-top.navbar-light.navbar-expand-lg.bg-light
    = link_to "Gathers", root_path, class: "navbar-brand"
    button.navbar-toggler type="button" data-toggle="collapse" data-target="#Navbar" aria-controls="Navbar" aria-expanded="false" aria-label="ナビゲーションの切り替え"
      span.navbar-toggler-icon
    .collapse.navbar-collapse#Navbar
      ul.navbar-nav.ml-auto
        li.nav-item
          = link_to "ホーム", root_path, class:"nav-link"
        li.nav-item
          = link_to "新規ユーザー", signup_path, class:"nav-link"
        li.nav-item
          a.nav-link href="#" ログイン
        li.nav-item
          a.nav-link href="#" ユーザー
          / = link_to "ユーザー", users_path, class:"nav-link"
        li.nav-item.dropdown
          a.nav-link.dropdown-toggle#navbarDropdown href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" マイアカウント
          .dropdown-menu aria-labelledby="navbarDropdown"
            a.dropdown-item href="#" プロフィール
            .dropdown-divider
            a.dropdown-item href="#" ログアウト

app/views/layouts/_jquery_bootstrap.html.slim
script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"
script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"
script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"

app/views/layouts/_support_IE9.html.slim
/![if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]

app/views/layouts/application.html.slim
doctype html
html lang="ja"
  head
    title
      = full_title(yield(:title))
    = render "layouts/head"
  body
    = render "layouts/header"
    .container
      = render "layouts/flash_messages"
      = yield
      = render "layouts/footer"
      = debug(params) if Rails.env.development?
    = render "layouts/jquery_bootstrap"

app/views/shared/_error_messages.html.slim
- if model.errors.any?

  #error_explanation
    .alert.alert-danger
      ' The form contains
      = pluralize(model.errors.count, "error")
      ul
        - model.errors.full_messages.each do |msg|
          li = msg

app/views/static_pages/home.html.slim
- provide(:title,"Home")

h1.main.text-center 発想を発信しよう

app/views/users/edit.html.slim
h1 Users#edit
p Find me in app/views/users/edit.html.slim

app/views/users/new.html.slim
- provide(:title, "Signup")

h1 新規登録

.row
  .col-md-6.offset-md-3
    = form_with(model: @user, url: signup_path, local: true) do |f|

      = render "shared/error_messages", model: f.object

      = f.label :name, "名前"
      = f.text_field :name, class:"form-control"

      = f.label :email, "メールアドレス"
      = f.email_field :email, class:"form-control", placeholder:"user@example.com"

      = f.label :password, "パスワード"
      = f.password_field :password, class:"form-control"

      = f.label :password_confirmation, "パスワード(確認)"
      = f.password_field :password_confirmation, class:"form-control"

      = f.submit "登録", class:"btn btn-primary"

app/views/users/show.html.slim
- provide(:title, @user.name)
.row
  aside.col-md-4
    section.user_info
      h1
        = gravatar_for @user
        = @user.name